### PR TITLE
Fixed action-helpers for handling internal errors

### LINKED ISSUE #624: getErrorMessege from response data breaks UI when trying to handle internal server error

### PR DESCRIPTION
**Pull request by amelentium**
dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/EventsExpress/EventsExpress/projects/2)

## Code reviewers

- [ ] @sand0

### Second Level Review

- [ ] @iuriikhrystiuk

## Summary of issue

Fixed getErrorMessage function in action-helpers.js for handling internal error responses

## Summary of change

1. Renamed getErrorMessege into getErrorMessage
2. Small changes in getErrorMessage to get the right data  

## Testing approach

ToDo

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

### CODE REVIEW

File: EventsExpress/ClientApp/src/components/helpers/action-helpers.js [hunk 1]
```diff
@@ -16,14 +16,14 @@ export const buildValidationState = async (responseData) => {
     return result;
 }
 
-export const getErrorMessege = async (responseData) => {
+export const getErrorMessage = async (responseData) => {
```
Comment (iuriikhrystiuk) [inline EventsExpress/ClientApp/src/components/helpers/action-helpers.js:19]: This function is exported. Are you sure there are no other references to it after rename?

**Review by iuriikhrystiuk — APPROVED** [review]
