### PR TITLE
Issue page date picker bug/ Issue page unfinite loading on wrong date enter

### LINKED ISSUE #900: Incorrect work with entering date to datepicker on issue page
**Date Time**
11-02-2021 19:40

**Priority**
Medium

**Environment:**
OS: Windows 10
Browser Chrome
Reproducible: when day in datepicker < 12

**Steps to Reproduce**
1.Go to https://eventsexpress-test.azurewebsites.net/ 
2. Login as "Admin".
2. Go to Issues page.
4. Write the date to datepicker(for example '02-05-2021').
5. Click to Search button.

**Expected result**
The date on Datepicker equals '02-05-2021'

**Actual result**
The date on Datepicker equals '05-02-2021'
**Screenshots**

https://user-images.githubusercontent.com/52419346/139918067-5f38bd9b-e4b1-47bf-8f1a-2d5b30c64824.mp4

### LINKED ISSUE #901: Endless loading when entering the wrong date on issue page
**Date Time**
11-02-2021 19:50

**Priority**
Medium

**Environment:**
OS: Windows 10
Browser Chrome
Reproducible: when day in datepicker > 12

**Steps to Reproduce**
1.Go to https://eventsexpress-test.azurewebsites.net/ 
2. Login as "Admin".
2. Go to Issues page.
4. Write the date to datepicker(for example '31-02-2021').
5. Click to Search button.

**Expected result**
Find 4 elements.

**Actual result**
Endless loading. 'Invalid% 20Date & page = 1' error is displayed in url.
**Screenshots**

https://user-images.githubusercontent.com/52419346/139919376-e47b1eb8-b034-41f3-aac0-abcb32330f0e.mp4

### PR DESCRIPTION
**Pull request by Apostall107**
dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/EventsExpress/EventsExpress/projects/2)

## Code reviewers

- @iuriikhrystiuk 

## Summary of issue

Wrong attitude of date picker and representation of date in store occurred unexpected results in work with date picker,.

## Summary of change

Added parseDate file to use  with component of KeyboardDatePicker.

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

#900
#901

### CODE REVIEW

File: EventsExpress/ClientApp/src/components/helpers/form-helpers/parseEuDate.js [hunk 1]
```diff
@@ -0,0 +1,19 @@
+const parseEuDate = (value) => {
```
Comment (iuriikhrystiuk) [inline EventsExpress/ClientApp/src/components/helpers/form-helpers/parseEuDate.js:3]: Why didn't you use moment here?

**Review by iuriikhrystiuk — APPROVED** [review]
