### PR TITLE
'take item' button correct work

### LINKED ISSUE #509: The user has no possibility to add items for related event.
**Date Time**
15-04-2021

**Priority**
High 

**Severity**
Major

**Environment:**
 OS: [Windows 10]
 Browser [Chrome 89]
 Reproducible: always

**Description**
'Add item' button is not worked and user has no possibility to add items for related events. 
 
**Pre-conditions**
1. Launch to https://eventsexpress-test.azurewebsites.net/home/events?page=1&status=active
2. Authorize as an existing user
3. Create the event

**Steps to Reproduce**
1. Click on the 'Profile' button on the left sidebar of the page.
2. Click on the created event
3. Click on the 'add item' button in the 'list of inventories' box

**Expected result**
 The pop-up window is opened to add the item after clicking on the 'add item' button

**Actual result**
The 'add item' is not worked in the 'list of inventories' box on the event page. The empty page is opened

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by amelentium**
dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/EventsExpress/EventsExpress/projects/2)

## Code reviewers

- [ ] @iuriikhrystiuk

### Second Level Review

- [ ] @sand0

## Summary of issue

Fixed 'Add item' button logic for non event-master user

## Summary of change

1. Added shouldComponentUpdate for check if user already taken the item
2. Remove unnecessary markItemAsWillTake
3. Fixed InventoryItemWrapper functions logic
4. Added seeding for unitsOfMeasuring into DbInitializer 

## Testing approach

ToDo

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

### CODE REVIEW

File: EventsExpress/ClientApp/src/containers/inventory-item.js [hunk 1]
```diff
@@ -24,9 +24,21 @@ class InventoryItemWrapper extends Component {
         this.onWillTake = this.onWillTake.bind(this);
     }
 
+    shouldComponentUpdate(nextProps, nextState) {
+        if (this.props === nextProps && this.state === nextState)
```
Comment (iuriikhrystiuk) [inline EventsExpress/ClientApp/src/containers/inventory-item.js]: You cannot check equality here, since the object memory address will be checked but not the actual values of the props. If you want to check exactly values of the props - you need to do it explicitly for every property of the props. Same for the sate.

File: EventsExpress/ClientApp/src/containers/inventory-item.js [hunk 2]
```diff
@@ -124,7 +133,9 @@ class InventoryItemWrapper extends Component {
                 <VisitorEditItemForm
                     onSubmit={this.onWillTake}
                     onCancel={this.onCancel}
-                    alreadyGet={alreadyGet - (this.state.isWillTake ? 0 : usersInventories.data.find(e => e.inventoryId === item.id).quantity || 0)}
+                    alreadyGet={alreadyGet - (usersInventories.data.find(e => e.userId === user.Id && e.inventoryId === item.id) === undefined
```
Comment (iuriikhrystiuk) [inline EventsExpress/ClientApp/src/containers/inventory-item.js]: Let's move this to a separate function - since it is quite complex and hard to read here. You can than use proper variables instead of doint the list traversal twice.

File: EventsExpress/ClientApp/src/containers/inventory-item.js [hunk 3]
```diff
@@ -24,9 +24,21 @@ class InventoryItemWrapper extends Component {
         this.onWillTake = this.onWillTake.bind(this);
     }
 
+    shouldComponentUpdate(nextProps, nextState) {
+        if (this.props === nextProps && this.state === nextState)
+            return false
+        if (this.props.usersInventories.isPending !== nextProps.usersInventories.isPending) {
+            const { item, user } = nextProps
+            if (!this.state.isWillTake && nextProps.usersInventories.data.some(e => e.userId === user.id && e.inventoryId === item.id))
+                this.onAlreadyGet()
```
Comment (iuriikhrystiuk) [inline EventsExpress/ClientApp/src/containers/inventory-item.js:32]: You are mutating the state based on the props that are coming in. Should it not go into the `componentDidUpdate` instead?

**Review by iuriikhrystiuk — APPROVED** [review]
