### PR TITLE
FixBug Validate

### LINKED ISSUE #626: [Contact us] Placing of the error message with an empty description field
**Date Time**
06-02-2021 12:15

**Priority**
Medium 

**Environment:**
OS: Windows 10 x64
Browser Google Chrome 90.0.4430.212
Reproducible: always
Build found: 20210601.7 

**Pre-conditions**

1. Move to https://eventsexpress-test.azurewebsites.net
2. Authorize as user 

**Steps to Reproduce**
1. Click on 'Contact us'
2. Add a 'Category' (e.g. Bug report)
3. Click on 'Submit' button

**Actual result**
The error message is devided into two rows, where 'Descriprion' is in the box and 'required' is under the box on the 'Contact us' page.

**Better result**

**Screenshots**
Actual result:

image

Better result:
image

### PR DESCRIPTION
**Pull request by PirogStanislav**
dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/EventsExpress/EventsExpress/projects/2)

## Code reviewers

- [ ] @iuriikhrystiuk

### Second Level Review

- [ ] @sand0

## Summary of issue

Fixed validate logic

## Summary of change

Now the validator throws the word "required + firstName"

## Testing approach

ToDo

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

### CODE REVIEW

**Review by iuriikhrystiuk — COMMENTED** [review]
I don't know if this is what expected to show to a user. I don't think he needs to know how we name the properties. Is there a backlog issue linked to this PR?

**Comment by PirogStanislav** [comment]
Tech Lead and product owner approved these changes on Thursday.

File: EventsExpress/ClientApp/src/components/contactAdmin/contactAdmin-component.js [hunk 1]
```diff
@@ -68,7 +68,7 @@ class ContactAdmin extends Component {
                                 className="form-control"
                                 component={renderTextArea}
                                 type="input"
-                                label="Description" />
+                               />
```
Comment (sand0) [inline EventsExpress/ClientApp/src/components/contactAdmin/contactAdmin-component.js:71]: shouldn't we pass the label props instead?

**Review by sand0 — APPROVED** [review]
