### PR TITLE
folder name and imports fixed

### LINKED ISSUE #471: Problem with incorrect name in editProfile and binded imports

### PR DESCRIPTION
**Pull request by stannydan**
dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/EventsExpress/EventsExpress/projects/2)

## Code reviewers

- [ ] @github_username

### Second Level Review

- [ ] @github_username

## Summary of issue

ToDo

## Summary of change

ToDo

## Testing approach

ToDo

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

### CODE REVIEW

File: EventsExpress/ClientApp/src/reducers/user.js [hunk 1]
```diff
@@ -1,12 +1,12 @@
...
-import { editBirthday } from '../actions/editProfile/birthday-edit-action';
-import { editGender } from '../actions/editProfile/gender-edit-action';
-import { editUsername } from '../actions/editProfile/userName-edit-action';
-import { changeAvatar } from '../actions/editProfile/avatar-change-action';
+import { addUserCategory } from '../actions/redactProfile/userCategory-add-action';
+import { addUserNotificationType } from '../actions/redactProfile/userNotificationType-add-action';
+import { editBirthday } from '../actions/redactProfile/birthday-edit-action';
+import { editGender } from '../actions/redactProfile/gender-edit-action';
+import { editUsername } from '../actions/redactProfile/userName-edit-action';
+import { changeAvatar } from '../actions/redactProfile/avatar-change-action';
```
Comment (v08uka) [inline EventsExpress/ClientApp/src/reducers/user.js]: How about making an index.js in the "redactProfile" folder and importing everything from there?

File: EventsExpress/ClientApp/src/containers/categories/SelectCategories.js [hunk 2]
```diff
@@ -1,7 +1,7 @@
 ﻿import React, { Component } from 'react';
 import { connect } from 'react-redux';
 import SelectCategories from '../../components/SelectCategories/SelectCategories';
-import setUserCategory from '../../actions/editProfile/userCategory-add-action';
+import setUserCategory from '../../actions/redactProfile/userCategory-add-action';
```
Comment (iuriikhrystiuk) [inline EventsExpress/ClientApp/src/containers/categories/SelectCategories.js:4]: Let's name it to be `changeProfile`, please.

File: EventsExpress/ClientApp/src/reducers/user.js (hunk 1 above)
Comment (stannydan) [reply EventsExpress/ClientApp/src/reducers/user.js]: Done!

**Review by iuriikhrystiuk — APPROVED** [review]
