### PR TITLE
#897 - Error on new event creation attempt, #903 - UI app does not handle 500 internal error correctly

### LINKED ISSUE #897: [Add event] Error on new event creation attempt.
**Date Time**
27-10-2021 16:30
**Priority**
High

**Environment:**
 OS: Windows 10
 Browser: OperaGX
 Reproducible: always
 Build found: 321727e
 
**Pre-conditions**
Lauch local project.

**Steps to Reproduce**
1. Login as "User".
2. Go to event cration page 'add event' button.
3. Fill the fields with next values:
Image: empty (untouched).
Organizer: default (pressed with the mouse to move up the label) .
Title: Test
Max Count Of Participants: default (2147483647).
Recurrent event: unchecked.
Public: unchecked.
Dates:  From: Current date.  To: Any date after current date.
Description: Test.
Hashtags: Gaming.
RadioButton: Map.
4. Click on 'Save'.
5. See error

**Expected result**
Creation of new user`s event.

**Actual result**
After long time waiting for loading page, Unhandled Rejection error accurs.
**Screenshots**
изображение_2021-10-27_164741

**Labels to be added** "Bug", Priority ("pri:Hight "), Severity ("severity:"), Type  ("Functional").

### LINKED ISSUE #903: UI app does not handle 500 internal error correctly.

### PR DESCRIPTION
**Pull request by idontwannawakeup**
dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/EventsExpress/EventsExpress/projects/2)

## Code reviewers

- [ ] @sand0 
- [ ] @iuriikhrystiuk 

### Second Level Review

- [ ] @Neckral 

## Summary of issue

In 897 there was an error with saving new event, this issue was reproducable, when Azure Storage Emulator was turned off.
Because of this photo couldn't upload, and server returned 500 Internal Server Error.
This error wasn't properly handled in UI app and Unhandled Rejection page was shown

## Summary of change

First of all, I changed response object from server for 500 Internal Server Error, so its pattern will match to 400 Bad Request response object. This allowed me to refactor buildValidationState and getErrorMessage functions. Now getErrorMessage uses buildValidationState to get message with error. Also, I added error handling in event form for case, when there is global form error (_error).
Then I changed edit_event function. Originally it used SubmissionError to display errors, but this didn't work for click on save button, because SubmissionError is handled by redux-form when form is submitted, and form is submitting by publish button. It was hard to submit form with two buttons, so I used callbacks for error and success cases.

## Testing approach

ToDo

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

#897 
#903

### CODE REVIEW

File: EventsExpress/ClientApp/src/actions/event/event-add-action.js [hunk 1]
```diff
@@ -26,15 +26,17 @@ export default function add_event() {
...
 
-export function edit_event(data) {
+export function edit_event(data, onError, onSuccess) {
     return async dispatch => {
         dispatch(getRequestInc());
         let response = await api_serv.editEvent(data);
-        if (!response.ok) {
-            throw new SubmissionError(await buildValidationState(response));
+        dispatch(getRequestDec());
+        if (!response.ok && onError && typeof onError === 'function') {
```
Comment (iuriikhrystiuk) [inline EventsExpress/ClientApp/src/actions/event/event-add-action.js]: This code can process success messages even if the response is not successful. Please split the check of the response and whether the parameter was specified. Also, you don't need to check for the function type - it's internal code and it will always be a function.

File: EventsExpress/ClientApp/src/containers/edit-event.js [hunk 2]
```diff
@@ -62,13 +69,13 @@ const mapStateToProps = (state) => ({
 
 const mapDispatchToProps = (dispatch) => {
     return {
-        edit_event: (data) => dispatch(edit_event(data)),
+        edit_event: (data, onError, onSuccess) => dispatch(edit_event(data), onError, onSuccess),
```
Comment (iuriikhrystiuk) [inline EventsExpress/ClientApp/src/containers/edit-event.js]: Since onError is not tied to an instance of a class - you can define it directly in this mapdispatchtoprops and remove the onSuccess parameter.

File: EventsExpress/ClientApp/src/containers/edit-event.js [hunk 3]
```diff
@@ -1,21 +1,28 @@
...
-        await this.props.edit_event({ ...validateEventForm(values), user_id: this.props.user_id, id: this.props.event.id });
-        this.props.alert('Your event has been successfully saved!');    
+        await this.props.edit_event({
+            ...validateEventForm(values),
+            user_id: this.props.user_id,
+            id: this.props.event.id
+        }, async response => {
+            throw new SubmissionError(await buildValidationState(response));
+        });
+        this.props.alert('Your event has been successfully saved!');
```
Comment (iuriikhrystiuk) [inline EventsExpress/ClientApp/src/containers/edit-event.js]: Shouldn't this alert be in the onSuccess?

Comment (idontwannawakeup) [reply EventsExpress/ClientApp/src/containers/edit-event.js]: Yes

File: EventsExpress/ClientApp/src/actions/event/event-add-action.js (hunk 1 above)
Comment (idontwannawakeup) [reply EventsExpress/ClientApp/src/actions/event/event-add-action.js]: Agree

**Review by iuriikhrystiuk — APPROVED** [review]
