### PR TITLE
#157 - fix bug, user cannot change gender and date of birth. Cannot c…

### LINKED ISSUE #157: User's personal data (gender and birth date) cannot be edit
**Date Time**
11-11-2020 20:00

**Priority**
Medium

**Description**
As a registered user I cannot change a Gender in my profile.

**Pre-conditions**
Be authorized as an ordinary user by link https://eventsexpress-test.azurewebsites.net/home/events?page=1.

**Steps to Reproduce**
1. Click on the button `Edit your profile`
2. Select 'gender' and change gender to the opposite
3. Select 'birth date' and choose the date '01-01-1980'
4. Press the `SUBMIT` button.

**Expected result**
Gender and birth date has been changed

**Actual result**
Gender and birth date were not changed
Error message `Failed`

**Environment:**
 - Windows 10
 - Browser Chrome 
 - Version 86.0.4240.183 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by OleksandrShchur**
#157-fix bug, user cannot change gender and date of birth. Cannot create private event.

### CODE REVIEW

File: EventsExpress/Controllers/UsersController.cs [hunk 1]
```diff
@@ -165,11 +165,12 @@ public async Task<IActionResult> Block(Guid userId)
...
         /// <response code="400">Edit process failed.</response>
         [HttpPost("[action]")]
-        public async Task<IActionResult> EditUsername(UserInfo userInfo)
+        public async Task<IActionResult> EditUsername(string name)
         {
-            var validator = new UserInfoNameValidator();
-
-            var validationResult = validator.Validate(userInfo);
+            var validator = new EditUserNameDtoValidator();
+            EditUserNameDto userName = new EditUserNameDto();
```
Comment (iuriikhrystiuk) [inline EventsExpress/Controllers/UsersController.cs]: Why not pass in the `EditUserNameDto` into the action method?

File: EventsExpress/Controllers/UsersController.cs [hunk 2]
```diff
@@ -161,15 +161,16 @@ public async Task<IActionResult> Block(Guid userId)
...
-        /// <param name="userInfo">Required.</param>
+        /// <param name="userName">Required.</param>
         /// <response code="200">Edit is succesful.</response>
         /// <response code="400">Edit process failed.</response>
         [HttpPost("[action]")]
-        public async Task<IActionResult> EditUsername(UserInfo userInfo)
+        public async Task<IActionResult> EditUsername(EditUserNameDto userName)
         {
-            var validator = new UserInfoNameValidator();
+            var validator = new EditUserNameDtoValidator();
```
Comment (iuriikhrystiuk) [inline EventsExpress/Controllers/UsersController.cs]: You don't need to inline validator calls. These will be done by registering fluent validation from `Startup.cs`.

**Review by iuriikhrystiuk — CHANGES_REQUESTED** [review]

**Review by iuriikhrystiuk — APPROVED** [review]
