### PR TITLE
Fixed issue with saving published event after editing. Divided logic of LocationMap

### LINKED ISSUE #573: When editing a published event and clicking on the save button, an error occurs
**Date Time**
05-05-2021 13:10

**Priority**
High

**Environment:**
 OS: Windows
 Browser: Google Chrome, Firefox
 Reproducible: always
 Build found: (e.g. tag)
 
**Pre-conditions**

Be authorized as a user

**Steps to Reproduce**

1. Select any existing published event listed and associated with the current user.
2. Click on the "Edit" button.
3. Select the "Map" option as the venue for the event.
3. Choose any location on the map by putting a point on it.
3. Click on the "Save" button.

**Expected result**
Saving and redirecting back to the event information form

**Actual result**
Error occurs, but the event is still saved, if try to come back to the event form using URL

### LINKED ISSUE #594: The circle and marker rendering doesn't work properly while changing radius or dragging and positioning
**Date Time**
15-05-2021 15:00

**Priority**
Medium

**Environment:**
 OS: Windows
 Browser: Google Chrome, Firefox
 Reproducible: always
 Build found: (e.g. tag)
 
**Pre-conditions**

Be authorized as a user.
Have a draft of an event or own any published event

**Steps to Reproduce**

1. Go to the filter panel
2. Click on the "Filter by location" button
3. See the premature drawing of the circle
OR
3. Click anywhere on the map to set the circle
4. Set any radius value (ex.1000km)
5. Zoom out/in the map several times
6. Reselect the position on the map
7. See incorrect rendering of the circle
OR
1. Select any published event or event draft
2. Set the marker on the map by selecting any point
3. Drag the marker to another location
4. See incorrect rendering of the map

**Expected result**
The circle is drawn with the appropriate radius. The map is rendered and displayed correctly after dragging a marker.

**Actual result**
The circle is properly displayed and rendered on the location map. The marker is dragged as expected.

**Screenshots**
Circle

### PR DESCRIPTION
**Pull request by alexanchez**
dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/EventsExpress/EventsExpress/projects/2)

## Code reviewers

- [x] @iuriikhrystiuk 

### Second Level Review

- [x] @sand0

## Summary of issue

The process of saving any published event after editing ends with an error. This error occurs due to the incorrect logic of the LocationMap field. There is a need to change this logic and divide LocationMap component into three different components which will allow to interact separately with the rendering of the marker and circle.
The marker and circle on the location map are not displayed and rendered properly.

## Summary of change

Changed methods used when editing and publishing an event. 
The logic of the location map field has been divided into three separate components.
Fixed issues with displaying and rendering of the marker and circle on the map.
Added alerts about successful creation, saving, publication and deletion of an event with corresponding messages.
Removed unnecessary functionality, redundant parameters, methods and imports.
Code refactoring has been performed.

## Testing approach

Tested manually.

## CHECK LIST
- [x]  PR is reviewed manually again (to make sure you have 100% ready code)
- [x]  I've checked new feature as logged in and logged out user if needed
- [x]  PR meets all conventions

### CODE REVIEW

File: EventsExpress/ClientApp/src/actions/event/event-add-action.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ export function edit_event(data) {
             throw new SubmissionError(await buildValidationState(response));
         }
         dispatch(setEventSuccess(true));
-        dispatch(getEvent(data));
+        dispatch(get_event(data.id));
```
Comment (sand0) [inline EventsExpress/ClientApp/src/actions/event/event-add-action.js]: I guess this was the correct fix. Is it? 
Why do we need this change to the previous functionality?

**Review by sand0 — CHANGES_REQUESTED** [review]

File: EventsExpress/ClientApp/src/actions/event/event-add-action.js (hunk 1 above)
Comment (alexanchez) [reply EventsExpress/ClientApp/src/actions/event/event-add-action.js]: Yes, indeed. Because this method already worked well. Probably, someone might have mistakenly changed its name and the parameter passed to this method. I can assume that this is due to the presence of two almost identical methods which have similar names. Nevertheless, this function requires passing only the identifier to this method, not the entire data. That's why I used exactly the "get_event" method.

Comment (iuriikhrystiuk) [reply EventsExpress/ClientApp/src/actions/event/event-add-action.js]: @alexanchez, could you please find from the history which issue it fixed and post it here? Also try your reproducing that issue with your fix please.

File: EventsExpress/ClientApp/src/actions/event/event-add-action.js [hunk 2]
```diff
@@ -45,7 +46,8 @@ export function publish_event(eventId) {
         let response = await api_serv.publishEvent(eventId);
         if (response.ok) {
             dispatch(setEventSuccess(true));
-            dispatch(getEvent(eventId));
+            dispatch(get_event(eventId));
```
Comment (iuriikhrystiuk) [inline EventsExpress/ClientApp/src/actions/event/event-add-action.js:49]: Again, are we sure we need to change this line? Doesn't it break previous fixes?

Comment (alexanchez) [reply EventsExpress/ClientApp/src/actions/event/event-add-action.js:49]: Yes, we are. Because the get_event method accepts an event id as a parameter, which comes to the publish_event method, while the getEvent takes the whole object. That's why we need to use exactly get_event method. Everything works as expected with these changes.

**Review by iuriikhrystiuk — DISMISSED** [review]

**Review by sand0 — DISMISSED** [review]

File: EventsExpress/ClientApp/src/components/event/event-filter.js [hunk 3]
```diff
@@ -33,7 +33,7 @@ class EventFilter extends Component {
                 categories: initialValues.categories,
                 statuses: initialValues.statuses,
                 radius: initialValues.radius,
-                selectedPos: initialValues.selectedPos != null ? initialValues.selectedPos : {lat: null, lng: null},
+                selectedPos: initialValues.selectedPos != null ? initialValues.selectedPos : { latitude: null, longitude: null }
```
Comment (sand0) [inline EventsExpress/ClientApp/src/components/event/event-filter.js:36]: do we still need `selectedPos `outside the map?

Comment (alexanchez) [reply EventsExpress/ClientApp/src/components/event/event-filter.js:36]: We use selectedPos only for filtering. It's just a convenient way to store the selected location along with other filter options.

**Review by sand0 — APPROVED** [review]
