### PR TITLE
Datepicker incorrect work

### LINKED ISSUE #448: Date-picker incorrect work
Incorrect display of initial data

### PR DESCRIPTION
**Pull request by ArchercodC**
dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/EventsExpress/EventsExpress/projects/2)

## Code reviewers

- [ ] @iuriikhrystiuk 

### Second Level Review

- [x] @sand0 

## Summary of issue

Datepicker worked incorrectly

## Summary of change

Changed type of datepicker and fixed transmission values in URL  

## Testing approach

ToDo

## CHECK LIST
- [x]  PR is reviewed manually again (to make sure you have 100% ready code)
- [x]  I've checked new feature as logged in and logged out user if needed
- [x]  PR meets all conventions

### CODE REVIEW

File: EventsExpress/ClientApp/src/components/event/event-filter.js [hunk 1]
```diff
@@ -125,7 +126,7 @@ class EventFilter extends Component {
                         <Button
                             fullWidth={true}
                             type="submit"
-                            color="primary"
+                            color="primary"
```
Comment (sand0) [inline EventsExpress/ClientApp/src/components/event/event-filter.js]: undo this change, pls

**Review by sand0 — CHANGES_REQUESTED** [review]

**Review by sand0 — APPROVED** [review]
