### PR TITLE
736 fix location field error displayng

### LINKED ISSUE #711: Splitting the location field in the event form into 2 fields: online meeting and map
It is necessary to split the location field to improve the validation process

### PR DESCRIPTION
**Pull request by rusnakvlad**
dev
## GitHub Project

* [Main GitHub Project ticket](https://github.com/EventsExpress/EventsExpress/projects/2)

## Code reviewers

- [ ] @iuriikhrystiuk 
- [ ] @sand0 

### Second Level Review

- [ ] @idontwannawakeup 

## Summary of issue

The warning message of location validation was not displayed on the front, also the validation of location was not even happening on the back.

## Summary of change
Was created location component which now handle logic of chousing location, also for location.onlineMeeting and location.Type we do not use any more component Field with property component, now is used directly the content which was passed to the property component of component Field. At the backend was refactored logic of location, so now we do not store in EventDto fields type, point and onlineMeeting, but only LocationDto. Also the type of onlineMeeting is not any more Uri, it was replaced by string.What about validation process, now the EventViewModel is validating directly in controller.
## Testing approach

ToDo

## CHECK LIST
- [ ]  PR is reviewed manually again (to make sure you have 100% ready code)
- [ ]  I've checked new feature as logged in and logged out user if needed
- [ ]  PR meets all conventions

#736

### CODE REVIEW

File: EventsExpress/ClientApp/src/components/location/location.js [hunk 1]
```diff
@@ -0,0 +1,88 @@
...
+      type: enumLocationType.online,
+      onlineMeeting: event.target.value == "" ? null : event.target.value,
+    });
+  };
+
+  returnLocationRender = () => {
+    const { value } = this.props.input;
+    if (value != null) {
+      if (value != "" && value.type == enumLocationType.map) {
+        return <Field name="location" component={LocationMapWithMarker} />;
```
Comment (iuriikhrystiuk) [inline EventsExpress/ClientApp/src/components/location/location.js]: You have to render the LocationWithMarker without the field as well.

File: EventsExpress/Mapping/EventMapperProfile.cs [hunk 2]
```diff
@@ -104,49 +98,100 @@ public EventMapperProfile()
...
+                }
+
+                if (e.Location.OnlineMeeting != null && e.Location.Type == LocationType.Online)
+                {
+                    locationDto.OnlineMeeting = e.Location.OnlineMeeting;
+                }
+
+                if (e.Location.Type == LocationType.Map)
+                {
+                    locationDto.Point = e.Location.Type == LocationType.Map ? PointOrNullEdit(e) : null;
```
Comment (iuriikhrystiuk) [inline EventsExpress/Mapping/EventMapperProfile.cs]: You already checked for the type above.

File: EventsExpress/ClientApp/src/components/location/location.js (hunk 1 above)
Comment (rusnakvlad) [reply EventsExpress/ClientApp/src/components/location/location.js]: Fixed

File: EventsExpress/Mapping/EventMapperProfile.cs (hunk 2 above)
Comment (rusnakvlad) [reply EventsExpress/Mapping/EventMapperProfile.cs]: Fixed

File: EventsExpress.Core/Services/EventService.cs [hunk 3]
```diff
@@ -230,7 +228,7 @@ public async Task<Guid> Edit(EventDto e)
                 .Include(e => e.EventSchedule)
                 .FirstOrDefault(x => x.Id == e.Id);
 
-            if (e.OnlineMeeting != null || e.Point != null)
+            if (e.Location != null)
             {
                 var locationDTO = Mapper.Map<EventDto, LocationDto>(e);
```
Comment (sand0) [inline EventsExpress.Core/Services/EventService.cs]: do we still need this mapping? I guess `locationDTO` is stored as `e.location` already

File: EventsExpress/EventsExpress.csproj.bak [hunk 4]
```diff
@@ -0,0 +1,93 @@
+﻿<Project Sdk="Microsoft.NET.Sdk.Web">
```
Comment (sand0) [inline EventsExpress/EventsExpress.csproj.bak]: delete this, pls

File: EventsExpress/Mapping/EventMapperProfile.cs [hunk 5]
```diff
@@ -104,49 +98,100 @@ public EventMapperProfile()
...
+            return new LocationDto()
+            {
+                Id = e.Id,
+                OnlineMeeting = e.EventLocation.OnlineMeeting,
+                Point = e.EventLocation.Point,
+                Type = e.EventLocation.Type,
+            };
+        }
+
+        private static LocationDto MapLocation(EventEditViewModel e)
```
Comment (sand0) [inline EventsExpress/Mapping/EventMapperProfile.cs]: Could we use polymorphism here to avoid code duplication?

**Review by sand0 — CHANGES_REQUESTED** [review]

File: EventsExpress.Core/Services/EventService.cs (hunk 3 above)
Comment (rusnakvlad) [reply EventsExpress.Core/Services/EventService.cs]: no, we don't need it any more, fixed

File: EventsExpress/EventsExpress.csproj.bak (hunk 4 above)
Comment (rusnakvlad) [reply EventsExpress/EventsExpress.csproj.bak]: done

File: EventsExpress/Mapping/EventMapperProfile.cs (hunk 5 above)
Comment (rusnakvlad) [reply EventsExpress/Mapping/EventMapperProfile.cs]: Maybe we could, but at this moment i don't know exactly how to do it. So, to avoid code dublication i used a new generic class which has a generic method to map to LocationDto

` 
public static class MapToLocationDto<T>
    {
        public delegate Point PointAction(T e);

        public static LocationDto Map(T eventViewModel, PointAction pointAction)
        {
            dynamic e;
            if (typeof(T) == typeof(EventCreateViewModel))
            {
                e = eventViewModel as EventCreateViewModel;
            }
            else if (typeof(T) == typeof(EventEditViewModel))
            {
                e = eventViewModel as EventEditViewModel;
            }
            else
            {
                throw new EventsExpressException("Cannot cast generic T to any type of Event View Model in Map to Location Dto");
            }

            var locationDto = new LocationDto();
            if (e.Location != null)
            {
                if (e.Location.Type != null)
                {
                    locationDto.Type = e.Location.Type;
                }

                if (e.Location.OnlineMeeting != null && e.Location.Type == LocationType.Online)
                {
                    locationDto.OnlineMeeting = e.Location.OnlineMeeting;
                }

                if (e.Location.Type == LocationType.Map)
                {
                    locationDto.Point = pointAction.Invoke(e);
                }
            }

            return locationDto;
        }
    }`

File: EventsExpress/ClientApp/src/components/helpers/form-helpers/location-map-with-marker.jsx [hunk 6]
```diff
@@ -5,18 +5,17 @@ import { LocationMap } from '.';
 
 export default function LocationMapWithMarker(props) {
     let initialPos = { lat: 50.4547, lng: 30.5238 };
-    if (props.input.value.latitude != undefined) {
-        initialPos = { lat: props.input.value.latitude, lng: props.input.value.longitude };
+    if (props.latitude != null) {
+        initialPos = { lat: props.latitude, lng: props.longitude };
```
Comment (sand0) [inline EventsExpress/ClientApp/src/components/helpers/form-helpers/location-map-with-marker.jsx:9]: It would be better to use `Object.assign()` here to merge with defaults. 

see detailed explanations [here|https://github.com/ryanmcdermott/clean-code-javascript#set-default-objects-with-objectassign]

File: EventsExpress/ClientApp/src/components/location/location.js [hunk 7]
```diff
@@ -0,0 +1,99 @@
+import React, { Component } from "react";
```
Comment (sand0) [inline EventsExpress/ClientApp/src/components/location/location.js:1]: I would recommend moving this over to the field-renderers package and group with all required utils. 
smth like:
```
form-helpers/
- location/
-- location-map-with-marker.jsx
-- event-location-renderer.jsx
-- index.jsx
```

File: EventsExpress/ClientApp/src/components/location/location.js [hunk 8]
```diff
@@ -0,0 +1,99 @@
...
+
+  onMapLocationChange = (mapLocation) =>{
+    this.props.input.onChange({
+      type:enumLocationType.map,
+      latitude:mapLocation.latitude,
+      longitude:mapLocation.longitude
+    })
+  }
+
+  returnLocationRender = () => {
```
Comment (sand0) [inline EventsExpress/ClientApp/src/components/location/location.js]: this should be simplified ad merged with the `render()` method

File: EventsExpress/Controllers/EventController.cs [hunk 9]
```diff
@@ -27,13 +29,15 @@ public class EventController : ControllerBase
...
+        private readonly IValidator<EventViewModel> _validator;
 
-        public EventController(IEventService eventService, IMapper mapper, ISecurityContext securityContextService, IPhotoService photoService)
+        public EventController(IValidator<EventViewModel> validator, IEventService eventService, IMapper mapper, ISecurityContext securityContextService, IPhotoService photoService)
         {
             _photoService = photoService;
             _eventService = eventService;
             _mapper = mapper;
             _securityContextService = securityContextService;
+            _validator = validator;
```
Comment (sand0) [inline EventsExpress/Controllers/EventController.cs]: Probably it would be better to use method-located DI since this is used in a single place... @iuriikhrystiuk, thoughts?

`public async Task<IActionResult> Publish(Guid eventId, [FromServices]IValidator<EventViewModel> validator)`

File: EventsExpress/Controllers/EventController.cs [hunk 10]
```diff
@@ -121,6 +125,27 @@ public async Task<IActionResult> Edit(Guid eventId, EventEditViewModel model)
...
+                throw new EventsExpressException("Event not found!");
+            }
+
+            EventViewModel ev = _mapper.Map<EventViewModel>(eventDto);
+
+            var validationResult = _validator.Validate(ev);
+            if (!validationResult.IsValid)
+            {
+                Dictionary<string, string> exept = new Dictionary<string, string>();
+                var p = validationResult.Errors.Select(e => new KeyValuePair<string, string>(e.PropertyName, e.ErrorMessage));
```
Comment (sand0) [inline EventsExpress/Controllers/EventController.cs]: use meaningful names, please

File: EventsExpress/Controllers/EventController.cs [hunk 11]
```diff
@@ -121,6 +125,27 @@ public async Task<IActionResult> Edit(Guid eventId, EventEditViewModel model)
...
+            if (eventDto == null)
+            {
+                throw new EventsExpressException("Event not found!");
+            }
+
+            EventViewModel ev = _mapper.Map<EventViewModel>(eventDto);
+
+            var validationResult = _validator.Validate(ev);
+            if (!validationResult.IsValid)
+            {
```
Comment (sand0) [inline EventsExpress/Controllers/EventController.cs]: this part can be moved into a separate private method... for instance `FormatValidationResult()`

File: EventsExpress/Mapping/EventMapperProfile.cs [hunk 12]
```diff
@@ -104,49 +98,81 @@ public EventMapperProfile()
...
+                }
+
+                if (e.Location.OnlineMeeting != null && e.Location.Type == LocationType.Online)
+                {
+                    locationDto.OnlineMeeting = e.Location.OnlineMeeting;
+                }
+
+                if (e.Location.Type == LocationType.Map)
+                {
+                    locationDto.Point = e.GetType() == typeof(EventCreateViewModel) ?
```
Comment (sand0) [inline EventsExpress/Mapping/EventMapperProfile.cs]: Why do we need this check for `EventCreateViewModel` here?

File: EventsExpress/Mapping/LocationMapperProfile.cs [hunk 13]
```diff
@@ -10,6 +10,9 @@ public LocationMapperProfile()
         {
             CreateMap<LocationDto, EventLocation>().ReverseMap();
             CreateMap<EventDto, LocationDto>()
```
Comment (sand0) [inline EventsExpress/Mapping/LocationMapperProfile.cs]: I guess we don't need this now

File: EventsExpress/Validation/EventValidator.cs [hunk 14]
```diff
@@ -1,5 +1,6 @@
 ﻿using System;
 using EventsExpress.Db.Entities;
+using EventsExpress.Db.Enums;
```
Comment (sand0) [inline EventsExpress/Validation/EventValidator.cs:2]: Do we use this `EventValidator : AbstractValidator<Event>` someplace?

File: EventsExpress/Mapping/EventMapperProfile.cs (hunk 12 above)
Comment (rusnakvlad) [reply EventsExpress/Mapping/EventMapperProfile.cs]: This check is needed because we have to know what method of point creation to invoke. [PointOrNullCreate] is supposed to be invoked on EventCreate, but [PointOrNullEdit] on EventEdit.

File: EventsExpress/Mapping/LocationMapperProfile.cs (hunk 13 above)
Comment (rusnakvlad) [reply EventsExpress/Mapping/LocationMapperProfile.cs]: CreateMap<LocationDto, EventLocation>().ReverseMap() is used in LocationService 
CreateMap<EventDto, LocationDto>() is used in EventService

File: EventsExpress/Validation/EventValidator.cs (hunk 14 above)
Comment (rusnakvlad) [reply EventsExpress/Validation/EventValidator.cs:2]: No, it is used nowhere, I will delete this

File: EventsExpress/Controllers/EventController.cs (hunk 11 above)
Comment (rusnakvlad) [reply EventsExpress/Controllers/EventController.cs]: yes it would be better, already did something

File: EventsExpress/Controllers/EventController.cs (hunk 10 above)
Comment (rusnakvlad) [reply EventsExpress/Controllers/EventController.cs]: done

File: EventsExpress/ClientApp/src/components/location/location.js (hunk 8 above)
Comment (rusnakvlad) [reply EventsExpress/ClientApp/src/components/location/location.js]: i need this function because if i render it directly on render() function some error occurs, i'll explin at daily meeting this

File: EventsExpress/Controllers/EventController.cs (hunk 9 above)
Comment (rusnakvlad) [reply EventsExpress/Controllers/EventController.cs]: done

File: EventsExpress/Controllers/EventController.cs (hunk 11 above)
Comment (rusnakvlad) [reply EventsExpress/Controllers/EventController.cs]: done

File: EventsExpress/Mapping/LocationMapperProfile.cs (hunk 13 above)
Comment (rusnakvlad) [reply EventsExpress/Mapping/LocationMapperProfile.cs]: done

File: EventsExpress/Mapping/EventMapperProfile.cs (hunk 12 above)
Comment (rusnakvlad) [reply EventsExpress/Mapping/EventMapperProfile.cs]: resolved

File: EventsExpress/ClientApp/src/components/location/location.js (hunk 7 above)
Comment (rusnakvlad) [reply EventsExpress/ClientApp/src/components/location/location.js:1]: resolved

File: EventsExpress/ClientApp/src/components/location/location.js (hunk 8 above)
Comment (rusnakvlad) [reply EventsExpress/ClientApp/src/components/location/location.js]: resolved

File: EventsExpress/Controllers/EventController.cs [hunk 15]
```diff
@@ -27,13 +30,15 @@ public class EventController : ControllerBase
         private readonly IEventService _eventService;
         private readonly IMapper _mapper;
         private readonly ISecurityContext _securityContextService;
+        private readonly IValidator<EventViewModel> _validator;
 
-        public EventController(IEventService eventService, IMapper mapper, ISecurityContext securityContextService, IPhotoService photoService)
+        public EventController(IValidator<EventViewModel> validator, IEventService eventService, IMapper mapper, ISecurityContext securityContextService, IPhotoService photoService)
```
Comment (iuriikhrystiuk) [inline EventsExpress/Controllers/EventController.cs]: Remove this validator from the constructor if you are injecting into methods then.

Comment (rusnakvlad) [reply EventsExpress/Controllers/EventController.cs]: done

**Review by iuriikhrystiuk — DISMISSED** [review]

**Review by iuriikhrystiuk — APPROVED** [review]

**Review by sand0 — APPROVED** [review]
